libs = ['gtest', 'gflags', 'pthread', 'boost_system', 'boost_thread', 'gomp', 'tcmalloc_minimal',  'boost_filesystem', 'boost_regex']
path = ['./', '../third_party/include/', '/usr/include']
env = Environment(CPPPATH=path,
                  CXXFLAGS="-std=c++11 -O2 -g -fopenmp -Wall -Wno-unused-function -Dprivate=public",
                  LIBPATH=['.', '../third_party/lib', '/usr/lib'],
                  LIBS=libs
                  )

sources = ['./*.cpp']
test_sources = [Glob('./test/*.cpp') ]

env.Program('./output/hash_index_test', test_sources + sources)
